# Generated by Django 4.2.7 on 2024-03-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date_posted',
        ),
    ]
